// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXR6cZy3kkr_WKf9j9Cq-PIANPG5LjQl0',
    appId: '1:794947646078:web:063a529afcb5485c8d9e2f',
    messagingSenderId: '794947646078',
    projectId: 'notes-app-e0266',
    authDomain: 'notes-app-e0266.firebaseapp.com',
    storageBucket: 'notes-app-e0266.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeNeNuYresPd2VRZbOBQ3VhX3spVmaow',
    appId: '1:794947646078:android:efd91e3ca66415098d9e2f',
    messagingSenderId: '794947646078',
    projectId: 'notes-app-e0266',
    storageBucket: 'notes-app-e0266.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXR6cZy3kkr_WKf9j9Cq-PIANPG5LjQl0',
    appId: '1:794947646078:web:198839a9ed54672f8d9e2f',
    messagingSenderId: '794947646078',
    projectId: 'notes-app-e0266',
    authDomain: 'notes-app-e0266.firebaseapp.com',
    storageBucket: 'notes-app-e0266.appspot.com',
  );
}
